
package android.aspen.leidos.com.sri.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DriverVehicleInformationData", isSet = false )
    public class DriverVehicleInformationData implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "id", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private String id = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "siteId", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private String siteId = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "driversLicenseNumber", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private String driversLicenseNumber = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "cdlNumber", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private String cdlNumber = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "vin", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private String vin = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "usdotNumber", isOptional =  false , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private String usdotNumber = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "plateNumber", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private String plateNumber = null;
                
  
        @ASN1Element ( name = "lat", isOptional =  false , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private Latitude lat = null;
                
  
        @ASN1Element ( name = "lon", isOptional =  false , hasTag =  true, tag = 8 , hasDefaultValue =  false  )
    
	private Longitude lon = null;
                
  
        @ASN1Element ( name = "fullDate", isOptional =  false , hasTag =  true, tag = 9 , hasDefaultValue =  false  )
    
	private DDateTime fullDate = null;
                
  
        
        public String getId () {
            return this.id;
        }

        

        public void setId (String value) {
            this.id = value;
        }
        
  
        
        public String getSiteId () {
            return this.siteId;
        }

        

        public void setSiteId (String value) {
            this.siteId = value;
        }
        
  
        
        public String getDriversLicenseNumber () {
            return this.driversLicenseNumber;
        }

        

        public void setDriversLicenseNumber (String value) {
            this.driversLicenseNumber = value;
        }
        
  
        
        public String getCdlNumber () {
            return this.cdlNumber;
        }

        

        public void setCdlNumber (String value) {
            this.cdlNumber = value;
        }
        
  
        
        public String getVin () {
            return this.vin;
        }

        

        public void setVin (String value) {
            this.vin = value;
        }
        
  
        
        public String getUsdotNumber () {
            return this.usdotNumber;
        }

        

        public void setUsdotNumber (String value) {
            this.usdotNumber = value;
        }
        
  
        
        public String getPlateNumber () {
            return this.plateNumber;
        }

        

        public void setPlateNumber (String value) {
            this.plateNumber = value;
        }
        
  
        
        public Latitude getLat () {
            return this.lat;
        }

        

        public void setLat (Latitude value) {
            this.lat = value;
        }
        
  
        
        public Longitude getLon () {
            return this.lon;
        }

        

        public void setLon (Longitude value) {
            this.lon = value;
        }
        
  
        
        public DDateTime getFullDate () {
            return this.fullDate;
        }

        

        public void setFullDate (DDateTime value) {
            this.fullDate = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DriverVehicleInformationData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            