
package android.aspen.leidos.com.sri.data;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Longitude" )
    public class Longitude implements IASN1PreparedElement {
    
            @ASN1Integer( name = "Longitude" )
            @ASN1ValueRangeConstraint ( 
		
		min = -1800000000L, 
		
		max = 1800000001L 
		
	   )
	   
            private Integer value;
            
            public Longitude() {
            }

            public Longitude(Integer value) {
                this.value = value;
            }
            
            public void setValue(Integer value) {
                this.value = value;
            }
            
            public Integer getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Longitude.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            